### ISSUE TITLE
Noticed changes in v1.0.7

### ISSUE THREAD

**Issue by navinkrishnan** [cap-js/change-tracking#101]
Hi,

In the Incidents-app test case for change-tracking, after deleting the incident following select query resulted in 0 results. This test case is passing with `@cap-js/change-tracking` `1.0.6`.

https://github.com/cap-js/incidents-app/blob/259abc1e41142f2d2f27d3c8cb09af0ee1e9aed1/xmpls/change-tracking.test.js#L125-L130

But checking with the upcoming release from the `main` branch of this repo (`1.0.7`), test case fails.
I would like to understand, if this is the expected behavior ?

If yes, I'm proposing the following change in test case. Please confirm if this is meaningful test.
```js
it('+ Test the status detail in ChangeView', async () => {
        const incidentChanges = await SELECT.from(ChangeView).where({
                entity: "sap.capire.incidents.Incidents",
                attribute: "status",
                keys: `ID=${draftId}`,
                modification: "delete"
            })
        expect(incidentChanges.length).to.equal(1);
      });
```

**Comment by nkaputnik** [comment]
Hello @navinkrishnan 
we did take a look at the test case, and we've seen that you already turned on the global switch to preserve deletes in line 88 of the test.
This will naturally invalidate the test you mentioned. We suggest to either turn the global switch off again before running this particular test, or even better, test against both cases.

Best,
Nick

**Comment by navinkrishnan** [comment]
Issue is reproducible with combination of `cds 8` and `change-tracking: 1.0.7`.
The global switch `preserveDeletes` seems to not take effect. It always preserves the delete history. Provided sample to @Sv7enNowitzki

**Comment by nkaputnik** [comment]
Hello @navinkrishnan 
it seems that CDS 8 has made changes to internal API's which break the behavior of how we detect deletes. 
So, we will need to fix this in the plugin, please do not change the tests, since they reflect the expected behavior.

Best,
Nick

**Comment by nkaputnik** [comment]
Hello @navinkrishnan 
we released a new version today, can you please take a look and see whether the tests now behave as intended?

Best,
Nick
