### ISSUE TITLE
@cap-js/change-tracking package downgrades cds 8v to 7.9.4v

### ISSUE THREAD

**Issue by Divya-Shanmugamb** [cap-js/change-tracking#102]
Hi,

In the incidents-app, before adding cap-js/change-tracking, the cds version is 8.
When we run 'npm add @cap-js/change-tracking', it downgrades the @sap/cds version to 7.9.4 

Due to which @cap-js/audit-logging is failing, as it requires cds v8.
We noticed v1.0.7 is getting ready from the main branch of this repo, will it get fixed with this version release? 

If yes, when can we expect this version to be published?

Regards,
Divya

**Comment by nkaputnik** [comment]
Hello @Divya-Shanmugamb 
we still have a bug with delete handling in CDS 8 which we are currently resolving. We do hope to get a release out, which works with CDS8 in the next week.

Best,
Nick

**Comment by nkaputnik** [comment]
New release is out now. Please try it our and see whether it fixes your issues.

Best,
Nick
