### ISSUE TITLE
[LMIT]Facing issue with CDS 8.1.1

### ISSUE THREAD

**Issue by C5324260** [cap-js/change-tracking#106]
Hi Team
We have a application called incident management but i see an error in building it and here are the logs 
15:34:21  info  shellExecute - npm error code ERESOLVE
15:34:21  info  shellExecute - npm error ERESOLVE unable to resolve dependency tree
15:34:21  info  shellExecute - npm error
15:34:21  info  shellExecute - npm error While resolving: @capire/incidents@1.0.0
15:34:21  info  shellExecute - npm error Found: @sap/cds@8.1.1
15:34:21  info  shellExecute - npm error node_modules/@sap/cds
15:34:21  info  shellExecute - npm error   @sap/cds@">=8" from the root project
15:34:21  info  shellExecute - npm error
15:34:21  info  shellExecute - npm error Could not resolve dependency:
15:34:21  info  shellExecute - npm error peer @sap/cds@"^7" from @cap-js/change-tracking@1.0.6
15:34:21  info  shellExecute - npm error node_modules/@cap-js/change-tracking
15:34:21  info  shellExecute - npm error   @cap-js/change-tracking@"*" from the root project
15:34:21  info  shellExecute - npm error
15:34:21  info  shellExecute - npm error Fix the upstream dependency conflict, or retry
15:34:21  info  shellExecute - npm error this command with --force or --legacy-peer-deps
15:34:21  info  shellExecute - npm error to accept an incorrect (and potentially broken) dependency resolution.
15:34:21  info  shellExecute - npm error
15:34:21  info  shellExecute - npm error
15:34:21  info  shellExecute - npm error For a full report see:

When the application was running on 7.9 it was going green but now i see this error in 8.1.1 

Please have a look
Regards,
Vinay C

**Comment by nkaputnik** [comment]
Hello @C5324260 
the current release doesn't work with CDS 8 yet, the next release, which will come very soon, should fix this.
In the meanwhile, you can manually just change the dependency in the package.json of the plugin to 8 to bridge the time.

Best,
Nick

**Comment by C5324260** [comment]
@nkaputnik 
When do we see the next release ?

Regards,
Vinay C

**Comment by nkaputnik** [comment]
New release is out now
