### ISSUE TITLE
 It is not possible to see the related attribute for which an attribute change is tracked

### ISSUE THREAD

**Issue by navdmad** [cap-js/change-tracking#108]
In our application we have an entity named Rule with ID, desc and Active(flag) as the schema. We are tracking the changes made to active flag and description. The issue is that we are not able to see from Change tracking which Rule was set from Active to Inactive (and vice-versa).

**Comment by nkaputnik** [comment]
Hello @navdmad 
you need to provide us some information to work with, before we can resolve such a vague issue.

Best,
Nick

**Comment by navdmad** [comment]
PFA the recording for the scenario. As described earlier, we have a Rule set with multiple rules as children. Each Rule has an Active flag which can be enabled/disabled and this change is captured in change history. The ask is if we can have the related Rule ID as well captured so that user can be clear as to which Rule of the Ruleset was enabled/disabled.

https://github.com/user-attachments/assets/844349f8-bb76-40c5-9f57-beff16375009

**Comment by nkaputnik** [comment]
Hello @navdmad 
this is documented very prominently in the readme
https://github.com/cap-js/change-tracking?tab=readme-ov-file#human-readable-ids

Best,
Nick
