### ISSUE TITLE
Changelog entries for "create"/"delete" and numeric values of 0 are not created

### ISSUE THREAD

**Issue by stockbal** [cap-js/change-tracking#111]
Hi,

currently if a numeric field is enabled to be change tracked, and a value of "0" is provided for that the field, it is available until the following point in the code, but will be skipped and not inserted into the changelog table.

https://github.com/cap-js/change-tracking/blob/e4cef968bd972064a84bd0daf58a70d34a8ef195/lib/change-log.js#L489

I expect the same thing will happen if `""` is passed for a String field.

Regards,
Ludwig

**Comment by Sv7enNowitzki** [comment]
Hello @stockbal 

The fix has been merged into main branch, it will be available at next release. So I'll close this issue, if you have question you can reopen it.

Best Regards,
Wenjun
