### ISSUE TITLE
Change History showing change for a Localised text field without making any change.

### ISSUE THREAD

**Issue by navdmad** [cap-js/change-tracking#113]
WE have a field Desc in our DB entity for a Rule. It is having the Localised annotation to support multiple languages. When logged in with English language, the field DESC on the UI shows the default value(in current example, English text). When logged in with a language for which we have a translated text available, the UI shows the corresponding text in DESC. When logged in with a. language for which no translation is available, the default text is displayed.
Now, if we go to the EDIT mode of a RULE, and do not make any change, still the DESC field is captured as changed.
PFA the recording for the behaviour.

https://github.com/user-attachments/assets/1709571f-3ec9-4c6c-b5af-5259f06ead28

**Comment by nkaputnik** [comment]
Hello @navdmad 
the change-tracking plugin works as intended.
In the video, we can see that the texts in the UI actually change, when you go in Edit-Mode, so we capture these changes, too. This is probably an issue with your UI, either draft handling, or Fiori-Annotations etc.
Please check whether these texts also change, when you do not enable the Change-Tracking plugin, to confirm.

Best,
Nick
