### ISSUE TITLE
Plugin not working when using CAP feature toggles

### ISSUE THREAD

**Issue by FrankVisuals** [cap-js/change-tracking#116]
We had the issue that within our repository the generated csn does not contain the UI Facets and the association to the changes.

We analyzed the issue using the [incidents app](https://github.com/cap-js/incidents-app) and found out that this happens when enabling the feature toggles as described [in the CAP docs](https://cap.cloud.sap/docs/guides/extensibility/feature-toggles#enable-feature-toggles).

Steps to reproduce:
- clone https://github.com/cap-js/incidents-app
- npm install
- npm install @sap/cds-mtxs @sap/hana-client
- add `"toggles": true` to the cds requires section in the package.json
- start the server

The actually weird part is: If I want to expose another association that's called `changes` it complains about a duplicate key, even though it doesn't show me a changes association in my generated csn.

**Comment by nkaputnik** [comment]
Hello @FrankVisuals 
this unfortunately is a gap in the current implementation of MTX. There is a solution outlined for solving this, but there is no timeline for delivery. We cannot fix this in the plugin on our own, we have to wait for MTX to deliver this.

Best,
Nick

**Comment by nkaputnik** [comment]
Closing, because we have a PR with a solution

**Comment by FrankVisuals** [comment]
Can you link the PR? @nkaputnik 

I don't see how / where this is fixed now. Please reopen the issue until it's fixed.

**Comment by nkaputnik** [comment]
Hello Frank,
I was referring to your own PR that is linked above. Since this is active and I'll pick it up before the next release, there is no need to this issue to remain open, right?

**Comment by FrankVisuals** [comment]
But my PR has not been merged yet, I'd keep this open until the actual problem is fixed.

Another finding from my side: You could hook into the middlewares  when having feature toggles enabled. This would allow you to get the tenant and feature toggle specific csn to adapt.

The root issue is not fixed with my PR, only informs about the underlying problem

**Comment by nkaputnik** [comment]
Hello @FrankVisuals 
The underlying issue is, that in MTX, the `ON LOADED` event is supressed. This not only causes issues with Feature toggles, but also with Extensibility in general. We are actively working with them to define a new exit specifically for plugins to hook into, but this is ongoing and may take a while.

Best,
Nick

**Comment by FrankVisuals** [comment]
Hey Nick,
thanks for the fast reply. I might be wrong about this - but the on loaded can never work as expected with features toggles enabled - right? As the CSN is dependent on the active features (which can be different in every request) there should be a different hook. Is it planned to have an additional event besides on loaded?

Best,
Frank

**Comment by nkaputnik** [comment]
Exactly, we aim for an additional event in the Model Provider to hook into...

**Comment by FrankVisuals** [comment]
Thanks!
