### ISSUE TITLE
Error with table with a key in navigation property

### ISSUE THREAD

**Issue by VanessaSap** [cap-js/change-tracking#134]
Hello,

When I try to implement Change Tracking on a table where the key is a navigation property, I get the following error:
 
"Error: CDS compilation failed (@sap/cds-compiler v5.4.0)
srv/admin-service.cds:408:45: Error: Unexpected usage of structured type “to_Rule” (in entity:“RulesDerivation”/column:“changes”/on)"
 
 entity RuleDerivation : managed {
    key to_Rule          :  Association to design.Rule
   ...
}
 
Could you help me understand if there’s a way to work around this problem?

**Comment by VanessaSap** [comment]
Let me know if you need more details

**Comment by jbm1991** [comment]
Did you find any solution to this problem as I've just run into exactly the same thing? Some further details for reproduction:

```
//schema.cds
namespace my.bookshop;

entity Books {
  key ID      : Integer;
      title   : String;
      stock   : Integer;
      authors : Association to one Authors;
      pages   : Association to many Pages
                  on pages.book = $self;
}

entity Authors {
  key ID    : Integer;
      name  : String;
      books : Association to many Books
                on books.authors = $self;
}

entity Pages {
  key book : Association to one Books;
  key num  : Integer;
      text : String;
}
```

```
// cat-services.cds
using my.bookshop as my from '../db/schema';

service CatalogService {
    @readonly
    entity Books   as projection on my.Books;

    @readonly
    entity Authors as projection on my.Authors;

    @readonly
    entity Pages   as projection on my.Pages;
}
```

```
// change-tracking.cds
using {CatalogService} from './cat-service';

annotate CatalogService.Books {
    stock @changelog;
    title @changelog;
}

annotate CatalogService.Authors {
    name @changelog;
}

annotate CatalogService.Pages {
    num  @changelog;
    text @changelog;
}

```

**Comment by VanessaSap** [comment]
> Did you find any solution to this problem as I've just run into exactly the same thing? Some further details for reproduction:
> 
> ```
> //schema.cds
> namespace my.bookshop;
> 
> entity Books {
>   key ID      : Integer;
>       title   : String;
>       stock   : Integer;
>       authors : Association to one Authors;
>       pages   : Association to many Pages
>                   on pages.book = $self;
> }
> 
> entity Authors {
>   key ID    : Integer;
>       name  : String;
>       books : Association to many Books
>                 on books.authors = $self;
> }
> 
> entity Pages {
>   key book : Association to one Books;
>   key num  : Integer;
>       text : String;
> }
> ```
> 
> ```
> // cat-services.cds
> using my.bookshop as my from '../db/schema';
> 
> service CatalogService {
>     @readonly
>     entity Books   as projection on my.Books;
> 
>     @readonly
>     entity Authors as projection on my.Authors;
> 
>     @readonly
>     entity Pages   as projection on my.Pages;
> }
> ```
> 
> ```
> // change-tracking.cds
> using {CatalogService} from './cat-service';
> 
> annotate CatalogService.Books {
>     stock @changelog;
>     title @changelog;
> }
> 
> annotate CatalogService.Authors {
>     name @changelog;
> }
> 
> annotate CatalogService.Pages {
>     num  @changelog;
>     text @changelog;
> }
> ```

Hello,
Unfortunately, I had to make a structural change to implement this history.

**Comment by nkaputnik** [comment]
Please see also here: https://github.com/cap-js/change-tracking/issues/130

**Comment by nkaputnik** [comment]
Closing for cleanup, keeping the referenced issue open
