### ISSUE TITLE
Adding the facet manually

### ISSUE THREAD

**Issue by wozjac** [cap-js/change-tracking#46]
Hello,

We have our app with annotations etc. change-tracking is not added to the view automatically.
Can it be added explicitly? 

BR,
Jacek

**Comment by nkaputnik** [comment]
Hello @wozjac 
yes, the facet can also be added manually. In principle, you just need to follow the steps in Line 7-17 in  `ìndex.cds` of the change-tracking plugin:

```cds
aspect aspect @(UI.Facets: [{
  $Type : 'UI.ReferenceFacet',
  ID    : 'ChangeHistoryFacet',
  Label : '{i18n>ChangeHistory}',
  Target: 'changes/@UI.PresentationVariant',
  ![@UI.PartOfPreview]: false
}]) {
  // Essentially: Association to many Changes on changes.changeLog.entityKey = ID;
  changes : Association to many ChangeView on changes.entityKey = ID;
  key ID  : UUID;
}
```
This is the UI Facet which should be added automatically to your UI. If that doesn't happen (FE configurations can vary greatly) you can add the Faced on your own. Please just remember to have the file in the requires path of your UI configuration.

Best,
NIck
