### ISSUE TITLE
Change Tracking library do not work with Numeric / Boolean fields

### ISSUE THREAD

**Issue by rahul03kumar** [cap-js/change-tracking#47]
Hello,

We have noticed that Change tracking fails on save request, if the tracked attribute is number or boolean.

Are there any patch expected to fix the problem.

Best Regards,
Rahul

**Comment by rahul03kumar** [comment]
Thanks, @nkaputnik

**Comment by nkaputnik** [comment]
Hello @rahul03kumar 
we have fixed the issue and it will be published in the next release (1.0.5) next week...
