### ISSUE TITLE
Change Tracking not working for Locale aspects

### ISSUE THREAD

**Issue by rahul03kumar** [cap-js/change-tracking#48]
Hello Team,

We are using a string field localized aspect to store descriptions in multiple languages. We have noticed that this scenario is not supported by change-tracking.

Kindly let us know if there is a roadmap to support this.

CDS Definition
```cds
@assert.unique: {businessKey: [name]}
entity PreDefinedText : cuid, managed {
  name : String;
  description : localized String;
```

Change tracking annotation:
```cds
annotate PreDefinedText.PreDefinedText with @title: 'PreDefinedText'{
    name        @changelog ;
    texts       @Changelog: [texts.description] @Common.Label: '{i18n>texts}';
}
```

Fiori App Screenshot:
We are changing the description. However, the values are not tracked.
<img width="1669" alt="image" src="https://github.com/cap-js/change-tracking/assets/152359374/19edad99-d57c-4bd7-a410-79c75b565d79">

Best Regards,
Rahul

**Comment by JocelynGu135** [comment]
Hi @rahul03kumar ,

As we discussed in email. Change tracking is already support for the localized modifier.
 
And you can do following changes in “change-tracking-v1.cds”
```cds
annotate PreDefinedText.PreDefinedText.texts with @title: 'Texts' {
    description  @changelog;               
}
```

And all the description changes will be tracked.
<img width="1663" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/0a1ac16d-c264-4273-9b3e-58d681ca5e93">

Best Regards
Jocelyn

**Comment by nkaputnik** [comment]
ToDo for myself: Add to documentation
