### ISSUE TITLE
@cap-js/change-tracking How to remove Change Log table from child entities object page

### ISSUE THREAD

**Issue by naveednoor786** [cap-js/change-tracking#52]
Hi,

we added this package in our solution and its working fine but we are facing issues that all child entities (Compositions) object page also start showing this change log table but there is no data shown specifically for that child entities and all change logs is being shown in the root level entity (which is fine to show in root entity).

But how to remove this table from the child entities or how to show data only for that child entities?

**Comment by nkaputnik** [comment]
Hello @naveednoor786 
can you please post your CDS file with the change log annotations here to take a lookl?

Best,
Nick
