### ISSUE TITLE
How to handle the visibility of Change History Section?

### ISSUE THREAD

**Issue by Rohit52080** [cap-js/change-tracking#66]
Hi Team, Can we handle the visibility of the Change History Section based on the user role?
I tried the Show Page Map feature of SAP Fiori Element, but the section is not visible (I guess because the section is created at the runtime). Is there any other way?

Please suggest.

**Comment by Rohit52080** [comment]
I was able to handle visibility in onAfterBinding method of Object Page Extension. Just wondering if we can handle this using .cds file of change tracking

**Comment by nkaputnik** [comment]
Hello @Rohit52080 
this is a UI runtime side effect, and if there is a possibility doing this via annotations, then the best channel to ask is the Fiori-Elements support channel over here: https://wiki.one.int.sap/wiki/display/UI/UI5+SUPPORT

Bdst,
Nick
