### ISSUE TITLE
Change logs not captured on composition level

### ISSUE THREAD

**Issue by wildflowerr1** [cap-js/change-tracking#67]
As continuation of https://github.com/cap-js/change-tracking/issues/64 

On the calesi/incidents-app, with the following code changes: 

<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/0a2c4a72-8469-4c7b-a8f2-6e577644d954">

I am able to achieve the following:
<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/23b66717-9e2f-4d5a-a0de-bcdd5651240b">

In other words, the end user is aware that changes are made for the composition "Conversation".

When I try to achieve the same thing within our project:
<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/badfcac9-5781-4a06-a4b6-e2a11acfe005">

It is not the case. You cannot see any change made on the composition.
If i directly annotate the entity the composition points to, e.g.
<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/35bacb70-9609-49a5-aef2-af2ca25a27d0">

And run the project as described here https://github.tools.sap/cap/issues/issues/15214

When I navigate to 
<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/85dd998b-8862-4e27-847b-f0c0650e70e4">

And modify the customerTenantAssignment through the value help:

<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/69257e2e-0da7-4dad-ba06-905ba2a867b8">

I get a log that tenant_id is logged
<img width="500" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/4ef11bbf-e536-4836-a20c-93f19be4805c">

But this information is scarce and I do not see from which composition the change is coming from.
How can I overcome that?

**Comment by wildflowerr1** [comment]
I'm also interested if the service path can be of use somehow: 
<img width="1728" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/aac6cc00-1523-4daf-98ce-0cd7f1cd6633">

**Comment by JocelynGu135** [comment]
Hi @wildflowerr1 

1. For the first question, in your screenshot, I find something incorrect for the changelog objectID definition.
In the following link, you will find now for change tracking, no need to use @changelog.objectID, just use @changelog is enough.
https://github.com/cap-js/change-tracking?tab=readme-ov-file#human-readable-ids

eg:
`annotate s4.S4DataRequests.customerTenantAssignments with @changelog: [ID] {
     tenent_ID @changelog;
};`

Maybe you can try to correct this one and check whether your issue can be resolved.

2. For the second one, I am not sure what is the meaning of "if the service path can be of use somehow" ?  Could you give me more explanation on this? Thanks


Best Regards
Jocelyn

**Comment by wildflowerr1** [comment]
Hi @JocelynGu135 

The following 

![image](https://github.com/cap-js/change-tracking/assets/156909896/db52ad02-f3ce-48f6-9142-9a56ec9987e3)

results in no change log at all. As for the service path --> I was looking for alternatives that give me the composition info I need. However, it is preferable to have it the standard way, e.g. by proper annotations.

Regards,
Violeta

**Comment by JocelynGu135** [comment]
Hi @wildflowerr1 ,

I think using "Object Type" column can meet your requirement.
The "Object Type" corresponds to "entity" attribute in "sap.changelog.ChangeView".
<img width="422" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/8cd3acc7-7493-4335-bb5a-9483bcab486d">

For the first step, need to remove the "UI.Hidden" for the "entity".

For the second step, give a human-readable object type.
eg:
`annotate 4.S4DataRequests.CustomerTenantAssignments with @title: '{i18n>CustomerTenantAssignments}';`

For the details how to define the human-readable object type, you can find the details in the following link.
https://github.com/cap-js/change-tracking?tab=readme-ov-file#human-readable-types-and-fields

Then you can see the composition of the changes will be displayed in the "Object Type" column.
<img width="1690" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/b5195229-4bc0-4fbd-90c4-ff7f629b24d7">

Best Regards
Jocelyn

**Comment by wildflowerr1** [comment]
Thanks @JocelynGu135 . This is what I wanted!
