### ISSUE TITLE
A field of type "Date" cannot be used for change tracking

### ISSUE THREAD

**Issue by 032660** [cap-js/change-tracking#68]
Hi colleagues,

If we are declaring a field in a CDS entity to be saved in the Changelog and this field has Data type:

@changelog
    dueDate                  : Date;

then it causes an error during saving the changes. What happens:

**const _formatCompositionContext = async function (changes, reqData) {
  const childNodeChanges = []

  for (const change of changes) {
    if (typeof change.valueChangedTo === "object") {**

In node_modules\@cap-js\change-tracking\lib\change-log.js  type of this field is considered to be an object (valueChangedTo is shown as “Thu Jan 01 1970 01:00:00 GMT+0100 (Central European Standard Time)”; valueDataType is "cds.Date") and is coverted to an Array:

**if (!Array.isArray(change.valueChangedTo)) {
        change.valueChangedTo = [change.valueChangedTo]
      }**

Then an attempt is done:
        **for (const childNodeChange of change.valueChangedTo) {
        const curChange = Object.assign({}, change)
        const path = childNodeChange._path.split('/')**

However childNodeChange is a string, not a real object, and does not have any path. So it dumps.

Could you please check why cds,Date is considered to be an object? May be it is concerning also other types?

Kind regards,
Elena Gurevitch

**Comment by nkaputnik** [comment]
Hello @032660 
this should have been fixed with release 1.0.5
Are you running the latest release?

Best,
Nick

**Comment by 032660** [comment]
Hi Nick,

Thank you for reply. I increased the version. But const path = childNodeChange._path.split('/') is still dumping.

childNodeChange is a string.

Kind regards,
Elena

**Comment by JocelynGu135** [comment]
Hi @032660 ,

Could you share your git repo or more detail information.

I have try `Date` type in my local project. All changes can be saved and logged successfully.
cds entity: 
entity Books : managed, cuid {
  title    : String(111);
  price    : Decimal;
  dueDate  : Date;
}

Change History UI Table:
<img width="1593" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/c75fac32-12b6-490b-a60b-c4d55e933a92">


Best Regards
Jocelyn

**Comment by 032660** [comment]
Hi Jocelyn,

Sorry, I think now it is not because of the framework. We are setting new Date() and it is represented in another format than date. I tested for another entity and it worked.

Nevertheless it was good to know that we should increase the release!

Thank you very much,
Elena

**Comment by JocelynGu135** [comment]
Hi @032660 Elena,

Thanks for your information. And I will close this issue. 


Best Regards
Jocelyn
