### ISSUE TITLE
CDS Compilation fails on mbt build when change-tracking is included

### ISSUE THREAD

**Issue by wildflowerr1** [cap-js/change-tracking#70]
More details of the initial problem are to be found here: [cap-issue-15399](https://github.tools.sap/cap/issues/issues/15399#issuecomment-5443100).

However, I was able to isolate the problem a bit further in the following branch: [chore-change-tracking/working-cds-build](https://github.tools.sap/customer-data-hub/cockpit/tree/chore-change-tracking/working-cds-build).

Steps to reproduce:
git clone https://github.tools.sap/customer-data-hub/cockpit.git
git fetch
git checkout [chore-change-tracking/working-cds-build](https://github.tools.sap/customer-data-hub/cockpit/tree/chore-change-tracking/working-cds-build)
npm i -g typescript ts-node
npm i -g @sap/cds-dk
npm i
npm i --prefix approuter

mbt build

As a result ```npm run build``` phase passes successfully when no change-tracking is involved:
<img width="800" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/d4c7cb1b-39e5-4b8c-97c9-8b561975d17f">

With slightest change, e.g. including change tracking within package.json and uncommenting the contents of db/ext-changes.cds:
<img width="800" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/4f2843b5-33d5-4613-9177-efddb93019a4">

<img width="1206" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/c06507c0-befe-48ec-96c9-fa37bd480b3d">

CDS compilation fails. Complete log is to be found here: [failing_logs.txt](https://github.com/cap-js/change-tracking/files/14382680/failing_logs.txt)

**Comment by JocelynGu135** [comment]
Hi @wildflowerr1 ,

I try to checkout the code [chore-change-tracking/working-cds-build](https://github.tools.sap/customer-data-hub/cockpit/tree/chore-change-tracking/working-cds-build), including change tracking within package.json and uncommenting the contents of db/ext-changes.cds, then running `npm run build`. But no error message show in my local terminal.
<img width="1223" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/9a2fd12a-85b7-4396-9f02-dc3ae92b92c8">

Are there any missing steps to reproduce this issue?

Best Regards
Jocelyn

**Comment by wildflowerr1** [comment]
Hi @JocelynGu135 ,

I resolved the issue myself by removing build parameters under cdh-srv. ```npm run build``` was present twice within our mta.yaml file which caused the misbehaviour.

**Comment by JocelynGu135** [comment]
Good to hear. Thanks for your update.
