### ISSUE TITLE
Is it possible to change formatting of the changed fields?

### ISSUE THREAD

**Issue by 032660** [cap-js/change-tracking#72]
Hello colleagues,

We defined changelog for decimal fields, for example

   @changelog
    cryptoAmount             : Decimal;

If the values are very small they are shown like

**Cryptocurrency Amount		4e-1**

Is it possible to provide some formatting to be used (are there any exits to format the values) ?  For example here we would prefer 0.4 because it is more user-friendly.

But I guess it is not possible.

And to combine an amount and a currency is also not possible, am I right?

I think the only way would be to have an additional string field where amount is formatted as desired but this is not good.

Kind regards,
Elena Gurevitch

**Comment by JocelynGu135** [comment]
Hi @032660 ,

1. I try to reproduce your issue in my local project. And for `Decimal` type field can be displayed with user-friendly value like (0.4) in both HANA and Sqlite3.

DB entity:
```
@changelog
price : Decimal;
```

Change History UI Table:
<img width="1669" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/d2dabc08-3d25-43d1-b9c6-0129e315ce59">
So is there a special logic for `cryptoAmount` field?

2. Your understanding is correct. Combine an amount and a currency is also not possible from the time being. 


Best Regards
Jocelyn

**Comment by 032660** [comment]
Hi Jocelyn,

Meanwhile some changes were done in our code and now amounts are shown correctly. 

You can close this issue.

Thank you very much for your support!

Kind regards,
Elena

**Comment by JocelynGu135** [comment]
Hi @032660,

Thanks for your update. And I will close the issue.

Best Regards
Jocelyn
