### ISSUE TITLE
How to hide change history?

### ISSUE THREAD

**Issue by 032660** [cap-js/change-tracking#75]
Hi colleagues,

we have two object pages in the same UI service annotation (app\payment\businessTransactions\annotations.cds) : one is used to show an existng business transaction. another to create or edit a draft business transaction. These are even different apps but they are built on the same UI service.

![Non-draft](https://github.com/cap-js/change-tracking/assets/149520814/09e57736-76e5-4c7d-a190-11ad42a33f2c)

![Draft](https://github.com/cap-js/change-tracking/assets/149520814/6367aa62-6b5b-4915-aa2d-dc3f784c6108)

We would like to show Change History only for the non-draft view. 

I saw that we could use 

annotate sap.changelog.aspect @(UI.Facets: [{
    $Type : 'UI.ReferenceFacet',
    ID    : 'ChangeHistoryFacet',
    Label : '{i18n>ChangeHistory}',
    Target: 'changes/@UI.PresentationVariant',
    ![@UI.PartOfPreview],
}]);

to make the change history to be shown at once.

Can we somehow use it to define visibility? I saw that UI.Hidden could be also defined here. But how can I provide the condition whether we are dealing with a draft? "IsActiveEntity" path is not valid .

I even tried to describe 'ChangeHistoryFacet' together with appplication facets - there "IsActiveEntity" path is known - but it did not have any affect.

Is there any possibility?

Kind regards,
Elena

**Comment by nkaputnik** [comment]
Hello @032660 
I would suggest to contact the UI5/Fiori Colleagues for this, since this is highly UI specific. As mentioned in your other isssue, we will provide an option to turn UI Faced gerenation off globally, but this is a highly fine grained operation, which we cannot deliver from out side.

Best,
Nick
