### ISSUE TITLE
Error Message with CDS 7 / lean_draft:false and change-tracking Plugin

### ISSUE THREAD

**Issue by itharth** [cap-js/change-tracking#76]
Dear team,

We have installed the plugin (https://github.com/cap-js/change-tracking) in our project and are using the latest version of CDS 7. Although we are using the current CDS 7 version, we are still using the old draft mode for our entities. This is currently supported by the attribute ("lean_draft": false).

The combination of CDS 7 / lean_draft:false and the plugin leads to problems. The error is located in the CDS 7 standard code, as shown in the screenshot attached to this note. The error message and the content of the object are also detailed in the screenshot.

Issue:
Error message when using CDS 7 / lean_draft:false with the change-tracking plugin

Cause:
Incompatibility between the plugin and CDS 7 standard code when using lean_draft:false

Steps to Reproduce:
Install the change-tracking plugin (https://github.com/cap-js/change-tracking)
Set "lean_draft": false in your CDS entity definitions
Create or update an entity
Observe the error message in the console
Expected Behavior:
The plugin should work seamlessly with CDS 7 / lean_draft:false
Actual Behavior:
An error message is displayed in the console

Screenshot:
Attached screenshot showing the error message and the content of the object
![code](https://github.com/cap-js/change-tracking/assets/90378662/48d974da-8dd7-4163-a2de-2a0d3652098a)
 
Additional Information:
Link to the GitHub repository of the change-tracking plugin (https://github.com/cap-js/change-tracking)

Request:
Please provide a solution for this issue.
Thank you for your time and support.

Sincerely

**Comment by JocelynGu135** [comment]
Hi @itharth ,

I try to reproduce your issue in my local project. I am using CDS 7.6.1 and setting lean_draft to false. But no error message is displayed in the console when create or update an entity.

lean_draft config:
<img width="298" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/b4e95cdd-b1a9-4fef-9e22-ec1e02e1b94e">

Create or update an entity successfully.
<img width="1105" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/924f310c-0bc6-493e-a9c9-27276e8a8c97">

Any steps I missing to reproduce this issue?

Best Regards
Jocelyn

**Comment by itharth** [comment]
Dear Jocelyn,
attached you will find our schema.cds because our data model is very complex
Please try it with this schema and we hope, that you will get the same error message like us.

[schema.zip](https://github.com/cap-js/change-tracking/files/14758562/schema.zip)

Otherwise we can also schedule a short teams call and we can show you the problem.

Thanks a lot and best regards
Hannes

**Comment by JocelynGu135** [comment]
Hi @itharth 

Could you give me your email address? And I will connect you offline.


Best Regards
Jocelyn
