### ISSUE TITLE
How to disable Change History for some UI service annotation

### ISSUE THREAD

**Issue by 032660** [cap-js/change-tracking#77]
Hi colleagues,

This question is similar to my previous ticket https://github.com/cap-js/change-tracking/issues/75 but nevertheless another one.

If Change History is declared for some entity then the tab "Change History" seems to appear on any object page which is dealing with this entity - for different UI services and apps.

This is very generic and of course comfortable (the application itself must not define anything - no any association to changes, no any facet etc.). But nevertheless sometimes it is not desired to show the change history on a certain screen or in a certain view.

Is there any possibility to disable Change History within one UI service annotation? If I set the aspect for ChangeHistoryFacet and set it to "hidden" then Change History disappears for all apps, not only for mine and not only for those dealing with the same entity.

Change History is somehow too generic and too global. It would be great to have a possibility to handle it for different apps and views individually.

Kind regards,
Elena

**Comment by nkaputnik** [comment]
Hello @032660 
we are working on specifying an additional option with the annotation to disable automatic UI generation, this should be ready within the next couple of weeks.

Best,
Nick

**Comment by nkaputnik** [comment]
Release 1.0.6 now added the possibility to disable the UI facet completely, please check it out...
