### ISSUE TITLE
Change tracking not showing

### ISSUE THREAD

**Issue by nandinigautam** [cap-js/change-tracking#83]
Hi Team,
We have managebusinesspartners/webapp/index.html application which when edited, the change tracking disappears and we can see no data in the change history , on commenting out the specified annotation for to show the 'show more' in change history.
The annotation in the change tracking file:

`annotate sap.changelog.aspect @(UI.Facets: [{
    $Type : 'UI.ReferenceFacet',
    ID    : 'ChangeHistoryFacet',
    Label : '{i18n>ChangeHistory}',
    Target: 'changes/@UI.PresentationVariant',
    ![@UI.PartOfPreview],
}]);`
Could you please look into the above.

Regards,
Nandini

**Comment by nkaputnik** [comment]
Hello @nandinigautam 
can you please create a reproducible example for me to look at? We need more information to help you.

Best,
Nick

**Comment by nandinigautam** [comment]
Hi @nkaputnik 

Sure, Here I am taking example of [/manageconsignment/webapp] which when edited shows change history .
![Screenshot 2024-04-18 082149](https://github.com/cap-js/change-tracking/assets/167090191/7ef4a6f7-acce-4823-b638-b8b59fba4639)
But Since I need the 'show more' button available in the change tracking, upon commenting this part of annotation from change-tracking file :

annotate sap.changelog.aspect @(UI.Facets: [{
   $Type : 'UI.ReferenceFacet',
   ID    : 'ChangeHistoryFacet',
   Label : '{i18n>ChangeHistory}',
   Target: 'changes/@UI.PresentationVariant',
   ![@UI.PartOfPreview],
}]);
we can see the show more button but no data in change-history.
![Screenshot 2024-04-18 082238](https://github.com/cap-js/change-tracking/assets/167090191/d1e6c77c-d312-449a-9337-8214b95bf750)
![Screenshot 2024-04-18 082247](https://github.com/cap-js/change-tracking/assets/167090191/fe990969-f169-4df3-9937-28d5c441b2ce)

Regards,
Nandini

**Comment by mkagarwal123** [comment]
@nkaputnik: Can you please help us on this issue as it is critical for the performance of our application

**Comment by nandinigautam** [comment]
@nkaputnik: Can you please help us on this issue as it is critical for the performance of our application

**Comment by nkaputnik** [comment]
Hello @mkagarwal123 
This is a known quirk of how Fiori Elements works since a couple of weeks ago. You need to hit the Mangifying glass icon in the search bar for the entries to be shown. 
We plan to address this with the Fiori Elements people ourselves, too, but for the time being, you will need to set somethin in manifest.json manually to achieve your desired behavior.

**Comment by nkaputnik** [comment]
Hello @nandinigautam 
I would strongly suggest taking this directly to the Fiori Elements team, since each additional voice will help prioritising this issue further up.

Best,
Nick
