### ISSUE TITLE
ChangeLog.ID shown in Filter and Sort of View Settings

### ISSUE THREAD

**Issue by GioDel** [cap-js/change-tracking#91]
Hi Team,

please check the attached screenshot. Technical field name ChangeLog.ID is shown for Filter and Sort of View Settings. I assume that should be either hidden or a readable label should be added.

Cheers, Giovanni
![ChangeLogID](https://github.com/cap-js/change-tracking/assets/25393300/ed429d73-ca16-4bc7-82d2-74c5669b9596)

**Comment by nkaputnik** [comment]
Hello @GioDel 
this was a missing UI annotation, this will be fixed with the next release.

Best,
Nick
